/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author migue
 */
public class V_Contrato_Servicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form V_Contrato_Servicio
     */
    public V_Contrato_Servicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lbl_accion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratoServicios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbltituloprincipal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClienteEmpresa = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnServicio = new javax.swing.JButton();
        lblMedPago = new javax.swing.JLabel();
        lblContratoServicio = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        txtMedioPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnMedioPago = new javax.swing.JButton();
        lblClientEmpre = new javax.swing.JLabel();
        btnClienteEmpresa = new javax.swing.JButton();
        lblServicio = new javax.swing.JLabel();
        btnguardar = new rojeru_san.RSButton();
        btncancelar = new rojeru_san.RSButton();
        btnactualizar = new rojeru_san.RSButton();
        btneliminar = new rojeru_san.RSButton();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lbl_accion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accion.setText("Nuevo contrato servicio");
        getContentPane().add(lbl_accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));

        tblContratoServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Servicio", "Cliente empresa", "Medio de pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContratoServicios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 610, 420));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        lbltituloprincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltituloprincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbltituloprincipal.setText("Contrato servicios");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar contrato servicios");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ContratoServicio.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltituloprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(lbltituloprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 60));

        txtClienteEmpresa.setEnabled(false);
        getContentPane().add(txtClienteEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 205, 25));

        txtServicio.setEnabled(false);
        getContentPane().add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 205, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Servicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cliente empresa");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnServicio.setText("ver");
        getContentPane().add(btnServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 30));

        lblMedPago.setText("idMedPago");
        getContentPane().add(lblMedPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        lblContratoServicio.setText("idConServ");
        getContentPane().add(lblContratoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtFecha.setDateFormatString("yyyy-MM-dd");
        txtFecha.setDoubleBuffered(false);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 230, 25));

        txtMedioPago.setEnabled(false);
        getContentPane().add(txtMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 205, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Medio de pago");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        btnMedioPago.setText("ver");
        getContentPane().add(btnMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 30));

        lblClientEmpre.setText("idClienEmpre");
        getContentPane().add(lblClientEmpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        btnClienteEmpresa.setText("ver");
        getContentPane().add(btnClienteEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 30));

        lblServicio.setText("idServ");
        getContentPane().add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnguardar.setText("Guardar");
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, -1));

        btncancelar.setBackground(new java.awt.Color(249, 23, 6));
        btncancelar.setText("Cancelar");
        btncancelar.setColorHover(new java.awt.Color(255, 59, 59));
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 170, -1));

        btnactualizar.setText("Actualizar");
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 170, -1));

        btneliminar.setBackground(new java.awt.Color(249, 23, 6));
        btneliminar.setText("Eliminar");
        btneliminar.setColorHover(new java.awt.Color(255, 59, 59));
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClienteEmpresa;
    public javax.swing.JButton btnMedioPago;
    public javax.swing.JButton btnServicio;
    public rojeru_san.RSButton btnactualizar;
    public rojeru_san.RSButton btncancelar;
    public rojeru_san.RSButton btneliminar;
    public rojeru_san.RSButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblClientEmpre;
    public javax.swing.JLabel lblContratoServicio;
    public javax.swing.JLabel lblMedPago;
    public javax.swing.JLabel lblServicio;
    public javax.swing.JLabel lbl_accion;
    public javax.swing.JLabel lbltituloprincipal;
    public javax.swing.JTable tblContratoServicios;
    public javax.swing.JTextField txtClienteEmpresa;
    public com.toedter.calendar.JDateChooser txtFecha;
    public javax.swing.JTextField txtMedioPago;
    public javax.swing.JTextField txtServicio;
    public javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
