/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author migue
 */
public class V_Cursos_Publicado extends javax.swing.JInternalFrame {

    /**
     * Creates new form V_Cursos_Publicado
     */
    public V_Cursos_Publicado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltituloprincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        txtCupo = new javax.swing.JFormattedTextField();
        txtHora = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursosPublicados = new javax.swing.JTable();
        btnVerCursos = new javax.swing.JButton();
        btnVerEmpleados1 = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblIdCurso = new javax.swing.JLabel();
        lblIdEmpleado = new javax.swing.JLabel();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        txtFechaFin = new com.toedter.calendar.JDateChooser();
        btnguardar = new rojeru_san.RSButton();
        btncancelar = new rojeru_san.RSButton();
        btnActualizar = new rojeru_san.RSButton();
        btneliminar = new rojeru_san.RSButton();
        lbl_accion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1396, 647));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        lbltituloprincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltituloprincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbltituloprincipal.setText("Cursos Publicados");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CursoPublicado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltituloprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(901, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltituloprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtCurso.setEnabled(false);
        getContentPane().add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 205, 25));
        txtCurso.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Curso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Fin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cupo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Lugar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));
        getContentPane().add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 205, 25));
        txtLugar.getAccessibleContext().setAccessibleDescription("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hora");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Empleado a cargo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, 30));

        txtEmpleado.setEnabled(false);
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 205, 25));
        txtEmpleado.getAccessibleContext().setAccessibleDescription("");

        txtCupo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 205, 25));
        txtCupo.getAccessibleContext().setAccessibleDescription("");

        txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 205, 25));
        txtHora.getAccessibleContext().setAccessibleDescription("");

        tblCursosPublicados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Curso", "Fecha de Inicio", "Fecha de Fin", "Cupo", "Cupo Disponible", "Lugar", "Hora", "Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCursosPublicados);
        if (tblCursosPublicados.getColumnModel().getColumnCount() > 0) {
            tblCursosPublicados.getColumnModel().getColumn(0).setMaxWidth(28);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 740, 470));

        btnVerCursos.setText("Ver");
        getContentPane().add(btnVerCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 50, 20));

        btnVerEmpleados1.setText("Ver");
        getContentPane().add(btnVerEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 50, 30));

        lblId.setText("Id");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblIdCurso.setText("IdCurso");
        getContentPane().add(lblIdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        lblIdEmpleado.setText("IdEmpl");
        getContentPane().add(lblIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));
        getContentPane().add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, 25));
        txtFechaInicio.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, 25));
        txtFechaFin.getAccessibleContext().setAccessibleDescription("");

        btnguardar.setText("Guardar");
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 170, -1));

        btncancelar.setBackground(new java.awt.Color(249, 23, 6));
        btncancelar.setText("Cancelar");
        btncancelar.setColorHover(new java.awt.Color(255, 59, 59));
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 170, -1));

        btnActualizar.setText("Actualizar");
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 170, -1));

        btneliminar.setBackground(new java.awt.Color(249, 23, 6));
        btneliminar.setText("Eliminar");
        btneliminar.setColorHover(new java.awt.Color(255, 59, 59));
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 170, -1));

        lbl_accion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accion.setText("Nuevo curso publicado");
        lbl_accion.setToolTipText("");
        getContentPane().add(lbl_accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.RSButton btnActualizar;
    public javax.swing.JButton btnVerCursos;
    public javax.swing.JButton btnVerEmpleados1;
    public rojeru_san.RSButton btncancelar;
    public rojeru_san.RSButton btneliminar;
    public rojeru_san.RSButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblId;
    public javax.swing.JLabel lblIdCurso;
    public javax.swing.JLabel lblIdEmpleado;
    public javax.swing.JLabel lbl_accion;
    public javax.swing.JLabel lbltituloprincipal;
    public javax.swing.JTable tblCursosPublicados;
    public javax.swing.JFormattedTextField txtCupo;
    public javax.swing.JTextField txtCurso;
    public javax.swing.JTextField txtEmpleado;
    public com.toedter.calendar.JDateChooser txtFechaFin;
    public com.toedter.calendar.JDateChooser txtFechaInicio;
    public javax.swing.JFormattedTextField txtHora;
    public javax.swing.JTextField txtLugar;
    // End of variables declaration//GEN-END:variables
}
