package Vista;


public class V_Principal extends javax.swing.JFrame {

    /**
     * Creates new form MDI_Food
     */
    public V_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        sub_mnu_Categoria_Cursos = new javax.swing.JMenuItem();
        sub_mnu_Cursos = new javax.swing.JMenuItem();
        sub_mnu_Cursos_Publicados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sub_mnu_Socursal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sub_mnu_Medio_Pago = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        sub_mnu_Servicios = new javax.swing.JMenuItem();
        sub_mnu_Tipo_Servicios = new javax.swing.JMenuItem();
        sub_mnu_Tipo_Contrato_Servicios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        sub_mnu_Empleado = new javax.swing.JMenuItem();
        sub_mnu_Persona = new javax.swing.JMenuItem();
        sub_mnu_Empresa = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        sub_mnu_Turno = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        sub_mnu_Puesto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Cursos.png"))); // NOI18N
        jMenu2.setText("Cursos");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Categoria_Cursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Categoria_Cursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/CategoriaCurso.png"))); // NOI18N
        sub_mnu_Categoria_Cursos.setText("Categorias cursos");
        jMenu2.add(sub_mnu_Categoria_Cursos);

        sub_mnu_Cursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Cursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Sub_Curso.png"))); // NOI18N
        sub_mnu_Cursos.setText("Cursos");
        jMenu2.add(sub_mnu_Cursos);

        sub_mnu_Cursos_Publicados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Cursos_Publicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/CursoPublicado.png"))); // NOI18N
        sub_mnu_Cursos_Publicados.setText("Cursos Publicados");
        jMenu2.add(sub_mnu_Cursos_Publicados);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Sucursal.png"))); // NOI18N
        jMenu1.setText("Sucursal");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.add(jSeparator3);

        sub_mnu_Socursal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Socursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Sucursal.png"))); // NOI18N
        sub_mnu_Socursal.setText("Sucursal");
        sub_mnu_Socursal.setToolTipText("");
        jMenu1.add(sub_mnu_Socursal);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/MedioPago.png"))); // NOI18N
        jMenu3.setText("Medio pago");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Medio_Pago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Medio_Pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/MedioPago.png"))); // NOI18N
        sub_mnu_Medio_Pago.setText("Medio pago");
        jMenu3.add(sub_mnu_Medio_Pago);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Servicios.png"))); // NOI18N
        jMenu5.setText("Servicios");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Servicios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Servicios.png"))); // NOI18N
        sub_mnu_Servicios.setText("Servicios");
        jMenu5.add(sub_mnu_Servicios);

        sub_mnu_Tipo_Servicios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Tipo_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/TipoServicio.png"))); // NOI18N
        sub_mnu_Tipo_Servicios.setText("Tipo de servicios");
        jMenu5.add(sub_mnu_Tipo_Servicios);

        sub_mnu_Tipo_Contrato_Servicios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Tipo_Contrato_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/ContratoServicio.png"))); // NOI18N
        sub_mnu_Tipo_Contrato_Servicios.setText("Contrato servicios");
        jMenu5.add(sub_mnu_Tipo_Contrato_Servicios);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Personal.png"))); // NOI18N
        jMenu4.setText("Personal");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Empleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Empleado.png"))); // NOI18N
        sub_mnu_Empleado.setText("Empleado");
        jMenu4.add(sub_mnu_Empleado);

        sub_mnu_Persona.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Persona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/ClientePersona.png"))); // NOI18N
        sub_mnu_Persona.setText("Cliente persona");
        jMenu4.add(sub_mnu_Persona);

        sub_mnu_Empresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/ClienteEmpresa.png"))); // NOI18N
        sub_mnu_Empresa.setText("Cliente empresa");
        jMenu4.add(sub_mnu_Empresa);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Turno.png"))); // NOI18N
        jMenu6.setText("Turno");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Turno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Turno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Turno.png"))); // NOI18N
        sub_mnu_Turno.setText("Turno");
        jMenu6.add(sub_mnu_Turno);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Puesto.png"))); // NOI18N
        jMenu7.setText("Puesto");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sub_mnu_Puesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_mnu_Puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMenuPrincipal/Puesto.png"))); // NOI18N
        sub_mnu_Puesto.setText("Puesto");
        jMenu7.add(sub_mnu_Puesto);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JMenuItem sub_mnu_Categoria_Cursos;
    public javax.swing.JMenuItem sub_mnu_Cursos;
    public javax.swing.JMenuItem sub_mnu_Cursos_Publicados;
    public javax.swing.JMenuItem sub_mnu_Empleado;
    public javax.swing.JMenuItem sub_mnu_Empresa;
    public javax.swing.JMenuItem sub_mnu_Medio_Pago;
    public javax.swing.JMenuItem sub_mnu_Persona;
    public javax.swing.JMenuItem sub_mnu_Puesto;
    public javax.swing.JMenuItem sub_mnu_Servicios;
    public javax.swing.JMenuItem sub_mnu_Socursal;
    public javax.swing.JMenuItem sub_mnu_Tipo_Contrato_Servicios;
    public javax.swing.JMenuItem sub_mnu_Tipo_Servicios;
    public javax.swing.JMenuItem sub_mnu_Turno;
    // End of variables declaration//GEN-END:variables
}
